{{ config( alias = 'ESG_SCORES_DATA') }}

SELECT 
CUSTOMER_ID as CUSTOMERID,
FIRST_NAME as F_NAME,
LAST_NAME AS L_NAME,
FIRST_ORDER AS F_ORDER,
MOST_RECENT_ORDER AS MR_ORDER,
NUMBER_OF_ORDERS AS NO_OF_ORDS,
TOTAL_ORDER_AMOUNT AS T_O_AMT,
CUSTOMER_LIFETIME_VALUE AS CUST_LT_V
FROM {{ref('SAT_ESG_SCORES')}} 