select 
    SRCTBL.*,
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS RECORD_LOAD_DATE,
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS RECORD_START_DATE
    ,NULL AS RECORD_END_DATE
    ,TRUE AS RECORD_IS_ACTIVE
from ( 
    {{ source('customer_data','RAW_ORDERS') }}
    ) AS SRCTBL